server:
  port: 7091
  servlet:
    context-path: /


sharding:
  jdbc:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding0?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    config:
      sharding:
        tables:
          tables:
            #水平分片单库分表
            t_user:  #t_user表
              key-generator-column-name: id  #主键
              actual-data-nodes: ds0.t_user${0..1}    #数据节点,均匀分布
              table-strategy:  #分表策略
                inline: #行表达式
                  sharding-column: sex
                  algorithm-expression: t_user${sex % 2}  #按模运算分配
        props:
          sql.show: true





mybatis:
  mapper-locations: classpath:mapper/*.xml



#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
